# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

# If port forwarding isn't working
# and you see a message like 
#
#Michaels-MacBook-Pro:ec2 cariaso$ vagrant up
#[default] Importing base box 'scientific'...
#[default] The guest additions on this VM do not match the install version of
#VirtualBox! This may cause things such as forwarded ports, shared
#folders, and more to not work properly. If any of those things fail on
#this machine, please update the guest additions and repackage the
#box.
#
#Guest Additions Version: 4.1.0
#VirtualBox Version: 4.2.8
#
#
# if you installed Vagrant as a package (rpm, deb, dmg,…)
#
# vagrant gem install vagrant-vbguest
# Or if you installed vagrant using RubyGems (gem install vagrant):
#
# gem install vagrant-vbguest
#
#
# http://blog.csanchez.org/2012/05/03/automatically-download-and-install-virtualbox-guest-additions-in-vagrant/




Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

#  config.vm.box = "scientific"
#  config.vm.box_url = "http://download.frameos.org/vagrant/sl6-64-nochef.box"
  config.vm.box = "Centos63"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.3-i386-v20130101.box"

  config.vm.forward_port 80,5680
  config.vm.forward_port 22,5622

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui


end
